#!/bin/bash

### Setup SSH key

mkdir -p /root/.ssh/
ssh-keyscan gitlab.com >> /root/.ssh/known_hosts
echo ${SSHKEY} | base64 --decode 2> nul > /root/.ssh/id_rsa

### Grab source code

mkdir -p /var/www/html
chown www-data:www-data /var/www/html
cd /var/www/html
git clone ${REPO} .
